trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  azureServiceConnection: "azureconnection"
  resourceGroupName: "myRG"
  webAppName: "mypythonapp1234"
  slotName: "green"
  pythonVersion: "3.14"

stages:
  # -------------------------------------------------------
  # Stage 1 - Build Python Application
  # -------------------------------------------------------

  - stage: Build
    displayName: "Build Python Application"

    jobs:
      - job: BuildApp
        displayName: "Build Application"
        steps:
          # Checkout Code
          - checkout: self

          # Python Version
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "$(pythonVersion)"
            displayName: "Use Python $(pythonVersion)"

          # Install Dependencies

          - script: |
              python --version
              pip --version
              pip install -r requirements.txt
            displayName: "Install Dependencies"

          # Create ZIP Package

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/app.zip"
              replaceExistingArchive: true
            displayName: "Create Application ZIP"

          # Publish Artifact

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)/app.zip"
              artifact: "pythonapp"
            displayName: "Publish Artifact"

  # -------------------------------------------------------
  # Stage 2 - Deploy to Green Slot
  # -------------------------------------------------------

  - stage: DeployGreen
    displayName: "Deploy to Green Slot"

    dependsOn: Build

    jobs:
      - deployment: DeployGreenSlot
        displayName: "Deploy Green Version"

        environment: "green"

        strategy:
          runOnce:
            deploy:
              steps:
                # Download Build Artifact

                - task: DownloadPipelineArtifact@2
                  inputs:
                    artifact: "pythonapp"
                    path: "$(Pipeline.Workspace)/pythonapp"
                  displayName: "Download Artifact"

                # Deploy to Green Slot

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    appType: "webAppLinux"
                    appName: "$(webAppName)"

                    deployToSlotOrASE: true

                    resourceGroupName: "$(resourceGroupName)"

                    slotName: "$(slotName)"

                    package: "$(Pipeline.Workspace)/pythonapp/app.zip"

                    runtimeStack: "PYTHON|3.14"

                  displayName: "Deploy to Green Slot"

  # -------------------------------------------------------
  # Stage 3 - Test Green Slot
  # -------------------------------------------------------

  - stage: TestGreen
    displayName: "Test Green Slot"

    dependsOn: DeployGreen

    jobs:
      - job: TestGreenApp
        displayName: "Test Green Application"

        steps:
          - script: |
              echo "Testing Green Slot"

              curl -f https://$(webAppName)-$(slotName).azurewebsites.net

            displayName: "Health Check Green Slot"

  # -------------------------------------------------------
  # Stage 4 - Swap Green to Production
  # -------------------------------------------------------

  - stage: Swap
    displayName: "Swap Green to Production"

    dependsOn: TestGreen

    jobs:
      - deployment: SwapSlots
        displayName: "Swap Deployment Slots"

        environment: "production"

        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureAppServiceManage@0

                  inputs:
                    azureSubscription: "$(azureServiceConnection)"

                    Action: "Swap Slots"

                    WebAppName: "$(webAppName)"

                    ResourceGroupName: "$(resourceGroupName)"

                    SourceSlot: "$(slotName)"

                    SwapWithProduction: true

                  displayName: "Swap Green to Production"

  # -------------------------------------------------------
  # Stage 5 - Verify Production
  # -------------------------------------------------------

  - stage: VerifyProduction
    displayName: "Verify Production"

    dependsOn: Swap

    jobs:
      - job: VerifyApp

        steps:
          - script: |

              echo "Testing Production Application"

              curl -f https://$(webAppName).azurewebsites.net

            displayName: "Test Production"
